// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgklI3HIvPpCDNRul4DEdwoRTychyUO4U',
    appId: '1:1042673240869:web:45da6a2e079ed144bea8cc',
    messagingSenderId: '1042673240869',
    projectId: 'my-farm-2023',
    authDomain: 'my-farm-2023.firebaseapp.com',
    storageBucket: 'my-farm-2023.appspot.com',
    measurementId: 'G-3EX4G1CJXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDEhnDwrKNDaHokVYBE6FlkMsBXpSjnf8',
    appId: '1:1042673240869:android:f858e1001ca589fdbea8cc',
    messagingSenderId: '1042673240869',
    projectId: 'my-farm-2023',
    storageBucket: 'my-farm-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQCr7i86L3FJdQxJz1ZThmhRwUL7QWi0c',
    appId: '1:1042673240869:ios:77c71a781eba7f81bea8cc',
    messagingSenderId: '1042673240869',
    projectId: 'my-farm-2023',
    storageBucket: 'my-farm-2023.appspot.com',
    iosClientId: '1042673240869-8b45nbgj63s99iu7d73p0ti4gi5afh15.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipes',
  );
}
